project:
  type: website

website:
  page-navigation: true
  title: "Výuka - Jan Caha"
  description: "Výukové materiály"
  site-url: "https://jancaha.github.io/vsb-vyuka/"

  open-graph: true

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright {{< var dates.year >}}, Jan Caha"

  sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    
    tools:
      - icon: github
        url: "https://github.com/JanCaha/vsb-vyuka"
      
    contents:
      - section: Předměty letní semestr
        contents:
        - href: pgis2.qmd
          text: Programování v GIS 2
        - href: idg.qmd
          text: Interpretace geodat
        - href: pdbs2.qmd
          text: Prostorové databázové systémy 2
      - section: Předměty zimní semestr
      - section: "Nástroje"
        contents:
        - href: vscode.qmd
          text: Visual Studio Code
        - href: linux-mint.qmd
          text: Linux Mint
        - href: osgeo4w.qmd
          text: OSGeo4W
      

format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

language: 
  crossref-fig-title: "Obr."
  crossref-tbl-title: "Tab."
  # https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml