project:
  type: website

website:
  page-navigation: true
  title: "Výuka - Jan Caha"
  description: "Výukové materiály"
  site-url: "https://jancaha.github.io/vsb-vyuka/"

  open-graph: true

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright {{< var dates.year >}}, Jan Caha"

  sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    
    tools:
      - icon: github
        url: "https://github.com/JanCaha/vsb-vyuka"
      
    contents:
      - section: Předměty letní semestr
        contents:
        - href: subjects/pgis2.qmd
          text: Programování v GIS 2
        - href: subjects/pvgis5.qmd
          text: Programování v GIS 5
        - href: subjects/idg.qmd
          text: Interpretace geodat
        - href: subjects/pdbs2.qmd
          text: Prostorové databázové systémy 2
      - section: Předměty zimní semestr
        contents:
        - href: subjects/pgis3.qmd
          text: Programování v GIS 3
        - href: subjects/pvgis4.qmd
          text: Programování v GIS 4
      - section: "Nástroje"
        contents:
        - href: tools/vscode.qmd
          text: Visual Studio Code
        - href: tools/linux-mint.qmd
          text: Linux Mint
        - href: tools/osgeo4w.qmd
          text: OSGeo4W
        - href: tools/github-copilot.qmd
          text: GitHub Copilot
      - section: Popisy
        contents:
        - href: descriptions/python.qmd
          text: Python
        - href: descriptions/python-traceback.qmd
          text: Python Error Traceback
          
format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

language: 
  crossref-fig-title: "Obr."
  crossref-tbl-title: "Tab."
  # https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml