name: env-project

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  # pgis2
  - GDAL
  - fiona
  - rasterio
  - shapely
  - pandas
  - geopandas
  - polars
  # quarto
  - jupyter
  - nbformat
  # VS Code extensions
  - black 
  - isort
  - mypy
  - pep8
  - flake8
  - pylint
  # SQL
  - psycopg
  # install using pip
  - pip:
    # pgis2
    - geopolars