name: env-project

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  # pgis2
  - GDAL
  - fiona
  - rasterio
  - shapely
  - pandas
  - geopandas
  - polars
  # quarto
  - jupyter
  - nbformat
