---
title: Interpretace geodat (IDG)
listing:
    id: prezentace
    contents: IDG/prezentace
    sort-ui: false
    filter-ui: false
    type: table
    date-format: iso
    sort:
        - "date"
    fields: [date, title] 
    field-display-names:
        title: "Prezentace"
        date: "Datum"
        author: "Autor"
filters:
   - include-code-files
---

## 游늮 콎e코en치 t칠mata

- 칰vod do jazyka R
- na캜칤t치n칤 dat do R
- manipulace s daty v R pomoc칤 bal칤ku `dplyr`, `tidyr`
- tvorba graf콢 v pomoc칤 `ggplot2`, dobr치 praxe tvorby graf콢 
- `Rmarkdown` a `Quarto`
- prostorov치 data v R, vektorory, rastry, vizualizace a operace s daty

## 游늼Prezentace

::: {#prezentace}
:::

## 游닇 Semin치rn칤 pr치ce

Vyberte si libovolnou otev콏enou datovou sadu pro 캛R, nap콏. z [N치rodn칤ho katalogu otev콏en칳ch dat](https://data.gov.cz/datov%C3%A9-sady) 캜i jin칠ho zdroje. Vytvo콏te bu캞 `Rmarkdown` nebo `Quarto` dokument, kter칳 bude obsahovat ve코kter칠 zpracov치n칤 dat a v칳stupy. S daty provede minim치ln캩 n치sleduj칤c칤:
- na캜ten칤 dat
- modifikace dat, v칳po캜et nov칳ch sloupc콢 nebo extrakce d칤l캜칤ch dat ze sloupc콢 do nov칳ch sloupc콢 (bal칤k `dplyr` a dal코칤)
- extrakce d칤l캜칤 캜치sti dat do men코칤 tabulky a jej칤 prezentace v dokumentu
- jeden graf se v코emi n치le쬴tostmi a korektn캩 vizualizovan칳 z dat (bal칤k `ggplot2`)
- jedna interaktivn칤 vizualizace (bal칤k `plotly` pro grafy, nebo `leaflet` pro prostorov치 data)
- statistick치 sumarizace/vyhodnocen칤 dat - shrnut칤, tabulka, vizualizace

## 游닄 Zdroje

- kniha [R for Data Science (2e)](https://r4ds.hadley.nz/) - shrnuje z치kladn칤 postupy datov칠 v캩dy (data science) v R
- kniha [Hands-On Programming with R](https://rstudio-education.github.io/hopr/) - programov치n칤 v R 
- kniha [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) - vizualizace dat - p콏칤klady v R
- kniha [Geocomputation with R](https://r.geocompx.org/) - z치klady pr치ce s geodaty v R
  
## Dal코칤 zaj칤mav칠 zdroje

- kniha [Data Visualization](https://socviz.co/) - vizualizace dat - p콏칤klady v R
- kniha [Statistical Inference via Data Science](https://moderndive.com/) - statistick칠 metody/postupy v R


## 游눹 Uk치zkov칠 k칩dy

## 游둰 Instalace

- R - [R CRAN](https://cran.r-project.org/bin/windows/base/)
- IDE - [RStudio](https://posit.co/download/rstudio-desktop/)

V RStudiu nainstalovat bal칤ky n치sleduj칤c칤m skriptem:
```{.r include="./IDG/skripty/00_packages_install.R"}
```