---
title: Programov치n칤 v GIS 2 (PGIS2)
listing:
    id: prezentace
    contents: PGIS2/prezentace
    sort-ui: false
    filter-ui: false
    type: table
    date-format: iso
    sort:
        - "date"
    fields: [date, title] 
    field-display-names:
        title: "Prezentace"
        date: "Datum"
        author: "Autor"
filters:
   - include-code-files
---

## 游늮 콎e코en치 t칠mata

- opakov치n칤 z치klad콢 Pythonu
-  knihovna GDAL/OGR

## 游늼Prezentace

::: {#prezentace}
:::

## 游닄 Zdroje

- data [Natural Earth](https://www.naturalearthdata.com/)
- [GDAL/OGR Cookbook](https://pcjericks.github.io/py-gdalogr-cookbook/)

## 游눹 Uk치zkov칠 k칩dy

## 游둰 Instalace

- management Pythonu - [Miniconda](https://docs.anaconda.com/free/miniconda/index.html)
- IDE - [Visual Studio Code](https://code.visualstudio.com/)
- extenze pro VS Code - Python, Python Debugger, Black Formatter, isort, autopep8, Flake8, Mypy Type Checker, Pylance, Pylint, autoDocstring - Python Docstring Generator
- instalace Conda environmentu

Definice environment souboru, nap콏. s n치zvem `env-pgis2.yaml` 
```{.yaml include="./PGIS2/soubory/conda-environment.yml"}
```

Z conda prompt n치sledn캩 spustit:
```{bash}
conda create -f env-pgis2.yaml
conda activate pgis2
```

## Dal코칤 

- z콏칤zen칤 칰캜tu na [Github](github.com), prim치rn캩 na soukroumou e-mailovou adresu a n치sledn캩 doplnit studentskou adresu
- po쮂멳치n칤 o studentsk칳 p콏칤stup na Github dle [캜l치nku](https://techcommunity.microsoft.com/t5/educator-developer-blog/step-by-step-setting-up-github-student-and-github-copilot-as-an/ba-p/3736279)
- ov캩콏en칤 n캩jakou dobou trv치 cca. 1-2 dny
- n치sledn캩 se lze ve **VS Code** pomoc칤 tohoto 칰캜tu p콏ihl치sit a m캩l by b칳t dostup칳 **GitHub Copilot**  