---
title: "Knihovny [fiona]{.software}, [rasterio]{.software}, [shapely]{.software}"
date: 2025-03-17
---

## Typy knihoven pro Python

- nativní knihovny - pouze Python kód
- kompilované knihovny - C, C++, Rust nebo i jiné jazyky
- nativní knihovny fungují automaticky všude, kompilované je nutné sestavit pro danou platformu a verzi Pythonu

## [fiona]{.software}, [rasterio]{.software}, [shapely]{.software}

- kompilované knihovny
- postavené nad [GDAL/OGR]{.software} (ne nad balíkem [osgeo]{.software})
- snaha aby pracovaly více jako Python knihovny a méně jako C++ kód
- o něco měně komplikované než přímé použití [GDAL/OGR]{.software} skrze [osgeo]{.software}, o něco horší spolupráce knihoven (zejména [fiona]{.software} a [shapely]{.software})

## [fiona]{.software}

- knihovna pro práci s vektorovými daty
- odstraňuje mnoho dílčích kroků, které jsou v [osgeo]{.software}
- souřadnicové systémy a transformace s knihovnou [pyproj]{.software}
- api není bohaté na práci s geometrií
- přístup např. ke struktuře vrstvy je velice jednoduchý
- nepodporuje vše co [osgeo]{.software}
- [dokumentace](https://fiona.readthedocs.io/en/stable/index.html)

## [shapely]{.software}

- knihovna založená na [GEOS]{.software}
- zpracování geometrií
- při využití s [fiona]{.software} nutné konverze mezi jejich typy
- [dokumentace](https://shapely.readthedocs.io/en/stable/index.html)

## Konverze geometrií

- modul `shapely.geometry`
- z [fiona]{.software} do [shapely]{.software} funkce `shape(feature.geometry)`
- z [shapely]{.software} do [fiona]{.software} funkce `mapping()`

## [rasterio]{.software}

- knihovna pro práci s rastrovými daty
- platí pro ni v podstatě to samé co pro [fiona]{.software}
- výrazné propojení s [numpy]{.software} (knihovna pro dvou a vícerozměrné matic)
- oproti [osgeo]{.software} jednodušší přístupy
- [dokumentace](https://rasterio.readthedocs.io/en/stable/index.html)
- problém s typováním - nutné hodně se opírat o dokumentaci

## Souřadnicové systémy a transformace

- klíčová operace v geoinformatice - převod dat mezi souřadnicovými systémy
- v [osgeo]{.software} {{< fa arrow-right >}} modul `osr` a třída `osr.SpatialReference`
- v knihovnách [fiona]{.software}/[rasterio]{.software} {{< fa arrow-right >}} knihovna [pyproj]{.software}
- [pyproj]{.software} je pythonový binding nad knihovnou [PROJ]{.software}

## [osr]{.software} - práce se souřadnicovými systémy

```{python}
# | eval: false
from osgeo import osr

srs = osr.SpatialReference()
srs.ImportFromEPSG(4326)

srs_dst = osr.SpatialReference()
srs_dst.ImportFromEPSG(5514)

# transformační objekt
transform = osr.CoordinateTransformation(srs, srs_dst)

# transformace bodu
x, y, _ = transform.TransformPoint(50.0, 14.0)
```

- pozor na pořadí souřadnic - [GDAL/OGR]{.software} standardně používá pořadí dle definice CRS (lat/lon pro EPSG:4326)

## [pyproj]{.software} - moderní přístup

```{python}
# | eval: false
import pyproj

crs_src = pyproj.CRS("EPSG:4326")
crs_dst = pyproj.CRS("EPSG:5514")

# transformační objekt
transformer = pyproj.Transformer.from_crs(crs_src, crs_dst, always_xy=True)

# transformace souřadnic
x, y = transformer.transform(14.0, 50.0)
```

- parametr `always_xy=True` zajistí pořadí souřadnic vždy jako **(x, y)** tj. **(lon, lat)** 
- bez tohoto parametru se pořadí řídí definicí CRS
- [pyproj]{.software} je přehlednější a doporučený přístup pro knihovny [fiona]{.software}, [shapely]{.software}, [geopandas]{.software}

## [GDAL/OGR]{.software} {{< fa times >}} [fiona]{.software}, [rasterio]{.software}, [shapely]{.software}

- [GDAL/OGR]{.software} má širší možnosti, ale práce je komplikovanější
- knihovny jsou zjednodušené a přístupnější
- nástroje `gdal.VectorTranslate()`, `gdal.Warp()`, `gdal.Translate()` atd. určitě využívat z `osgeo`
- základní modifikace či zpracování dat je v 90% případů snadnější z knihoven 
- komplexní situace lze řešit přímo použítím [osgeo]{.software}
- používat princip **KISS** (Keep it simple, stupid!)  -- začít s jednoduchou verzí, dokud funguje a upgradovat, posouvat dál, pouze pokud je to nutné
   
# Dotazy? {.center}