---
title: "Kontroly a formátování kódu"
date: 2026-03-16
year: 2026
---

## Kontroly kódu

- kontrola syntaxe, dobré praxe, formátování
- kontrola kvality kódu
- kontrola typů
- a další
- balíčky a extenze pro [VSCode]{.software} ale i pro [PyCharm]{.software} a další IDE

## Chyby při kontrole kódu

- nemusí se jednat o chyby, které by vyvolaly chybu při běhu programu/skriptu
- ale o chyby, které by mohly vést k chybám
- např. špatné pojmenování proměnné, nevyužité proměnné, špatné formátování kódu
- špatné typy proměnných
- špatné použití funkcí
- je vhodné se těmto chybám vyhnout a předcházet jim 
- ve [VS Code]{.software} se tyto chyby zobrazují jako podtržení kódu (v různých barvách, dle vážnosti a typu chyby)

## Chyby v kódu

- překlep v proměněné, který způsobí chybu při běhu programu, ale editor ho může odhalit už při psaní kódu
- zvýrazní neznámou proměnnou

```python
def area(width: float, height: float) -> float:
    return width * heigth
```

- editor zvýrazní překlep `heigth`, i když se soubor zatím nespouští.

## [pep8]{.software}

- kontroly stylu kódu proti **PEP 8**
- neprovádí logickou kontrolu kódu
- mezery v kódu, délka řádků, pojmenování proměnných, atd.
- příklad: `myFunctionName` je v Pythonu méně vhodné, doporučené je `my_function_name`. [pep8]{.software} upozorní na nesprávný styl pojmenování

## [flake8]{.software}

- kontrola stylu kódu i možných chyb
- kontrola přehnané komplexity kódu
- příklad: `import numpy as np`, ale v souboru ho nikde nepoužijete. [flake8]{.software} nahlásí nevyužitý import

## [pylint]{.software}
- kontrola stylu kódu i možných chyb
- vynucuje kódovací standardy, hledá i příklady špatné praxe
- nejkomplexnější kontrola kódu, s detailním hodnocením a reporty
- příklad: funkce má 12 argumentů a více vnořených podmínek. [pylint]{.software} upozorní na horší čitelnost a navrhne refaktoring

## MyPy

- statická kontrola typů proměnných u typovaného kódu
- někdy je nutné explicitně přetypovat proměnné, což lze udělat pomocí funkce `typing.cast()`

```python
from typing import Dict
def fn() -> Dict[str, int]:
    return {"klíč": "hodnota"}  # chyba: hodnota není int
```
- [MyPy]{.software} odhalí chybu při kontrole typů

## MyPy - přetypování

- někdy vzniká neshoda mezi typy, které MyPy očekává, a typy, které jsou v kódu
- obvykle se jedná o situace, kdy MyPy nedokáže správně určit typ proměnné, nebo když se typ proměnné mění v průběhu kódu
- často v situacích, kdy se používají binding knihovny, které s typy pracují jinak než MyPy očekává 
- nutné tzv. přetypování proměnné, kdy explicitně definujeme, jaký typ proměnná má

## MyPy - přetypování - ukázka

```python
import typing

# přetypování proměnné
promenna = typing.cast(NovaTrida, promenna)

# za tímto kódem už je proměnná typu NovaTrida
if isinstance(promenna, NovaTrida):
    ...

# za tímto kódem už je proměnná typu NovaTrida
assert isinstance(promenna, NovaTrida)
```

## Formátování kódu

- úprava kódu do standardizovaného formátu
- úprava importů

```text
# před formátováním
import sys,os

def add( a,b  ):
 return a+b
```

```python
# po formátování
import os
import sys


def add(a, b):
    return a + b
```

## [black]{.software} a [isort]{.software}

- extenze pro [VS Code]{.software}
- existují situace, kdy je formátování kódu v konfliktu s kontrolami kódu 
- fungují automaticky, jen vhodná kontrola nastavení ve [VS Code]{.software}
- parametry pro [black]{.software} a [isort]{.software} lze nastavit v `pyproject.toml`

## Konfigurace 

- lze buď v nastavení [VS Code]{.software}
- nebo v souboru `pyproject.toml`, který je v kořenovém adresáři projektu, kde nástroje nastavení načtou


## Konfigurace v [VS Code]{.software} v `settings.json`

```json
"flake8.args": [
    "--max-line-length",
    "160"
],
"pylint.args": [
    "--disable=E0611",
    "--max-line-length=160"
],
"isort.args": [
    "--profile",
    "black",
    "--line-width",
    "120"
],
"black-formatter.args": [
    "--line-length",
    "120"
]
```

## Konfigurace v `pyproject.toml`

```toml
[tool.flake8]
exclude = [".git", "__pycache__", "tests/*"]
max-line-length = 120
ignore = "W293,W504"

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "redefined-outer-name",
    "no-name-in-module",
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
    "invalid-name",
    "too-many-arguments",
    "attribute-defined-outside-init",
]

[tool.mypy]
follow_imports = "silent"
ignore_missing_imports = true
show_column_numbers = true
no_pretty = true
no_strict_optional = true

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
skip_gitignore = true
```

# Dotazy? {.center}