---
title: "Matplotlib"
date: 2025-04-28
year: 2025
---

# Matplotlib

## [Matplotlib]{.software}

- v [Pythonu]{.software} v podstatě standard na tvorbu vizualizací a grafů
- napsáno v [Pythonu]{.software} + optimalizace náročných části v [C/C++]{.software}
- odděluje 3 hlavní složky
  - interní model grafu
  - API pro programátory
  - vykreslovací backend 
- rozdělení umožňuje snadnou rozšiřitelnost
- pracuje dobře s [numpy]{.software} i [pandas]{.software}

## Komponenty 

- `Artist` - základní třída, všechno co je vidět se od ní odvozuje
- `Figure` - celý obrázek grafu
- `Axes` - samotný graf (něco co má osy)
- jeden `Figure` může obsahovat vícero `Axes` - např. dva grafy vedle sebe

## Backend

- interaktivní - třeba pro programy s **GUI**, nebo i z python skriptů (trochu nešťastné, protože skript se neukončí dokud se obrázek nezavře)
- statický - tvorba obrázků v různých formátech 
- **Qt5Agg, TkAgg, WebAgg** {{<fa times>}} **Agg, PDF, SVG, PS**

```python
import matplotlib
matplotlib.use('Agg') 
```

## Stylování a konfigurace

- buď přímo součást kódu (může být zdlouhavé a opakující se)
- použití globálního stylu v souboru `matplotlibrc` - soubor se hledá buď v aktuální projektu nebo v uživatelském adresáři
- předpřipravené styly

```python
import matplotlib
matplotlib.style.use('ggplot')
```

## Dva způsoby použití

- submodul `matplotlib.pyplot` kde pracujeme s jedním grafem
  - všechny volané funkce pak modifikují jeden graf
  - vhodné pro menší skripty a základní ukázky
- objektový přístup - tvorba `Figure` a `Axes` a jejich modifikace 
  - vhodné pro komplexnější grafy, či situace kdy tvoříme vícero grafů v rámci skriptu

```python
import matplotlib as mpl
# obrázek s 2 grafy - 1 řádek, 2 sloupce
# velikost obrázku je v palcích
fig, axs = mpl.pyplot.subplots(1, 2, figsize=(16, 8))
```

- prvek `axs` je ve skutečnosti pole, jednotlivých prvků s osami, takže přistupujeme jako `axs[0]` atd.

## Objektový přístup

- jednotlivé modifikace voláme přímo jako metody prvků `Figure` a `Axes`
- přehlednější a lépe přenositelné
- metody `Axes` např. `set_xlabel(), set_ylabel()`, `grid(), legend()` či `bar(), scatter(), plot()`
- metody `Figure` např. `show(), savefig()`, `suptitle()`

## Ukázky

- galerie na [webu projektu](https://matplotlib.org/stable/gallery/index.html) obsahuje i kód
- vyhledávání na githubu pomocí importu knihovny
- hodně pomůže i [Copilot]{.software} s dobrou specifikací dotazu

## Rozšíření

- existují další knihovny postavené nad [Matplotlib]{.software}
    - [seaborn]{.software} - [ukázky](https://seaborn.pydata.org/examples/index.html) 
    - [plotnine]{.software} - [ukázky](https://plotnine.org/gallery/)
- obvykle úprava API do nějakého *"vhodnějšího"* formátu

# Plotnine

## [plotnine]{.software} - co to je

- knihovna pro [Python]{.software} inspirovaná [ggplot2]{.software} z [R]{.software}
- používá koncept **Grammar of Graphics**
- graf se skládá z vrstev pomocí operátoru `+`
- vhodné zejména pro rychlou analytickou vizualizaci z [pandas]{.software} DataFrame
- renderuje přes [Matplotlib]{.software} backend

## Jak funguje systém (Grammar of Graphics)

- systém je založen na skládání několika částí grafu
- `data` {{< fa arrow-right >}} tabulka, ze které čteme hodnoty
- `aes(...)` {{< fa arrow-right >}} mapování sloupců na vizuální vlastnosti (`x`, `y`, `color`, ...)
- `geom_*` {{< fa arrow-right >}} jaký typ značek se vykreslí (`geom_point`, `geom_line`, `geom_col`)
- `stat_*` {{< fa arrow-right >}} volitelné statistické transformace
- `facet_*`, `theme_*`, `labs(...)` {{< fa arrow-right >}} rozdělení do panelů, vzhled, popisky

## Mentální model tvorby grafu

- 1) vyberu datový rámec
- 2) namapuji proměnné přes `aes(...)`
- 3) přidám geometrii (`geom_*`)
- 4) doplním měřítka, popisky a téma
- 5) volitelně rozdělím graf na panely (`facet_wrap`, `facet_grid`)

```python
from plotnine import aes, geom_point, ggplot, labs, theme_minimal

p = (
    ggplot(df, aes(x="delay", y="distance", color="carrier"))
    + geom_point(alpha=0.6)
    + labs(
        title="Delay vs distance",
        x="Delay (min)",
        y="Distance (km)",
        color="Carrier",
    )
    + theme_minimal()
)

p
```

## [plotnine]{.software} vs [Matplotlib]{.software} (kdy použít co)

- [plotnine]{.software}: deklarativní zápis, rychlé skládání běžných analytických grafů
- [Matplotlib]{.software}: detailní kontrola každého prvku a komplexní customizace
- častý postup v praxi:
  - explorace dat a standardní grafy v [plotnine]{.software}
  - speciální finální vizualizace v [Matplotlib]{.software}

# Dotazy? {.center}
