---
title: Interpretace geodat (IDG)
aliases: 
  - ./IDG/index.html
  - ./IDG/skripty/index.html
  - ./IDG/prezentace/index.html
listing:
    - id: prezentace
      contents: IDG/prezentace
      sort-ui: false
      filter-ui: false
      type: table
      date-format: iso
      sort:
        - "date"
      fields: [date, title] 
      field-display-names:
        title: "Prezentace"
        date: "Datum"
        author: "Autor"
    - id: codes
      contents: IDG/skripty/description.yaml
      sort-ui: false
      filter-ui: false
      type: table
      date-format: iso
      sort:
          - "date"
          - "path" 
      fields: [date, title] 
      field-display-names:
          title: "Skript"
          date: "Datum"
          author: "Autor"
filters:
   - include-code-files
---

## Řešená témata{.topics}

- úvod do jazyka R
- načítání dat do R
- manipulace s daty v R pomocí balíku `dplyr`, `tidyr`
- tvorba grafů v pomocí `ggplot2`, dobrá praxe tvorby grafů 
- `Rmarkdown` a `Quarto`
- prostorová data v R, vektorory, rastry, vizualizace a operace s daty

## Prezentace{.presentations}

::: {#prezentace}
:::

## Seminární práce{.seminar-work}

Vyberte si libovolnou otevřenou datovou sadu pro ČR, např. z [Národního katalogu otevřených dat](https://data.gov.cz/datov%C3%A9-sady) či jiného zdroje. Vytvořte buď `Rmarkdown` nebo `Quarto` dokument, který bude obsahovat veškteré zpracování dat a výstupy. S daty provede minimálně následující:

- načtení dat
- modifikace dat, výpočet nových sloupců nebo extrakce dílčích dat ze sloupců do nových sloupců (balík `dplyr` a další)
- extrakce dílčí části dat do menší tabulky a její prezentace v dokumentu
- jeden graf se všemi náležitostmi a korektně vizualizovaný z dat (balík `ggplot2`)
- jedna interaktivní vizualizace (balík `plotly` pro grafy, nebo `leaflet` pro prostorová data)
- statistická sumarizace/vyhodnocení dat - shrnutí, tabulka, vizualizace

## Zdroje{.sources}

- kniha [R for Data Science (2e)](https://r4ds.hadley.nz/) - shrnuje základní postupy datové vědy (data science) v R
- kniha [Hands-On Programming with R](https://rstudio-education.github.io/hopr/) - programování v R 
- kniha [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) - vizualizace dat - příklady v R
- kniha [Geocomputation with R](https://r.geocompx.org/) - základy práce s geodaty v R
  
### Další zajímavé zdroje

- kniha [Data Visualization](https://socviz.co/) - vizualizace dat - příklady v R
- kniha [Statistical Inference via Data Science](https://moderndive.com/) - statistické metody/postupy v R


## Ukázkové kódy{.codes}

::: {#codes}
:::


## Instalace{.instals}

- R - [R CRAN](https://cran.r-project.org/bin/windows/base/)
- IDE - [RStudio](https://posit.co/download/rstudio-desktop/)

V RStudiu nainstalovat balíky následujícím skriptem:
```{.r include="./IDG/skripty/00_packages_install.R"}
```