---
title: Prostorové databázové systémy 2 (PDBS2)
listing:
   - id: codes
     contents: PDBS2/skripty/description.yaml
     sort-ui: false
     filter-ui: false
     type: table
     date-format: iso
     sort:
       - "date"
     fields: [date, title] 
     field-display-names:
       title: "Skript"
       date: "Datum"
       author: "Autor"
   - id: prezentace
     contents: PDBS2/prezentace
     sort-ui: false
     filter-ui: false
     type: table
     date-format: iso
     sort:
       - "date"
       - "path"
     fields: [date, title] 
     field-display-names:
       title: "Prezentace"
       date: "Datum"
filters:
   - include-code-files
---

## Řešená témata{.topics}

- Oracle 
- Instalace a připojení k PostgreSQL, načtení dat z CSV a prostorová data skrze GDAL

## Prezentace{.presentations}

::: {#prezentace}
:::

## Zdroje{.sources}

- [PostgreSQL Manuál](https://www.postgresql.org/docs/14/index.html)
- [PostGIS Manuál](https://postgis.net/docs/manual-3.4/)

## Data ke stažení{.data-sources}

- [GPKG s vrstvami okresů a krajů](./PDBS2/soubory/uzemni_jednotky.gpkg)
- [CSV s údaji o počtu obyvatel](./PDBS2/soubory/obyvatele_roky.csv)
- [CSV s převodním číselníkem z RUIAN do ČSÚ](./PDBS2/soubory/ciselnik_csu_ruian.csv)

## Ukázkové kódy{.codes}

::: {#codes}
:::

## Instalace PostregSQL{.instals}

- viz odkaz [Linux Mint](../tools/linux-mint.qmd) - potřebujeme jednak akktuální GIS softwary a PostgreSQL (detaily na stránce)

### Docker

Pro provozování instance PostgreSQL s PostGIS lze použít i Docker kontejner. Ideálně využít `docker compose` se souborem s nastavením:

```yaml
version: "3.5"

services:
  postgres:
    container_name: postgis
    image: postgis/postgis:16-master
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - cesta_k_složce_na_disku:/data/postgres
    ports:
      - "5432:5432"
```

Stačí upravit `volumes` na složku na disk, kde se budou ukládat data z PostgreSQL a případně upravit nastavení uživatele a hesla.