---
title: Programování v GIS 3 (PGIS3)
listing:
    - id: prezentace
      contents: PGIS3/prezentace
      sort-ui: false
      filter-ui: false
      type: table
      date-format: iso
      sort:
          - "date"
      fields: [date, title] 
      field-display-names:
          title: "Prezentace"
          date: "Datum"
          author: "Autor"
    - id: codes
      contents: PGIS3/skripty/description.yaml
      sort-ui: false
      filter-ui: false
      type: table
      date-format: iso
      sort:
          - "date"
      fields: [date, title] 
      field-display-names:
          title: "Skript"
          date: "Datum"
          author: "Autor"
---

## Řešená témata{.topics}

- [ArcPy]{.software} knihovna
- funkce pro vypisování seznamů prvků `arcpy.List*()`
- popis objektů [ArcPy]{.software} pomocí `arcpy.Describe()`
- kurzory v [ArcPy]{.software} pro vektorová data
- třída geometrie v [ArcPy]{.software} 
- rastrová data v [ArcPy]{.software}
- tvorba vlastních balíků (+ jejich tetování)
- tvorba vlastních toolboxů a nástrojů

## Seminární práce{.seminar-work}

Sestavte Python skript, které provede libovolné netriviální zpracování prostorových dat, dle vlastního výběru. Ve skriptu využijte knihovnu [ArcPy]{.software}. Záhlaví skriptu bude obsahovat popis funkčnosti - co skript dělá. Skript odevzdejte emailem před posledním cvičením. Funkčnost skriptu bude prezentována na posledním cvičení.


## Prezentace{.presentations}

::: {#prezentace}
:::

## Zdroje{.sources}

- [API ArcPy for ArcGIS Pro](https://pro.arcgis.com/en/pro-app/latest/arcpy/main/arcgis-pro-arcpy-reference.htm)

## Data ke stažení{.data-sources}

- ukázková data ke knize [Programming ArcGIS Pro with Python – 2nd Edition](https://geospatialtraining.com/books/programming-arcgis-pro-with-python-2nd-edition/)

## Ukázkové kódy{.codes}

::: {#codes}
:::