---
title: Programování v GIS 2 (PGIS2)
aliases:
  - ./PGIS2/index.html
  - ./PGIS2/skripty/index.hmtl
  - ./PGIS2/prezentace/index.html
filters:
   - include-code-files
listing:
    - id: prezentace
      contents: PGIS2/prezentace
      sort-ui: false
      filter-ui: false
      type: table
      date-format: iso
      sort:
          - "date"
      fields: [date, title] 
      field-display-names:
          title: "Prezentace"
          date: "Datum"
          author: "Autor"
    - id: codes
      contents: PGIS2/skripty/description.yaml
      sort-ui: false
      filter-ui: false
      type: table
      date-format: iso
      sort:
          - "date"
          - "path"
      fields: [date, title] 
      field-display-names:
          title: "Skript"
          date: "Datum"
          author: "Autor"
---

## Řešená témata{.topics}

- opakování základů [Pythonu]{.software} 
- knihovna [GDAL/OGR]{.software}
- knihovny [rasterio]{.software}, [fiona]{.software}, [shapely]{.software}
- Github Copilot - otestování a využití
- funkce, objekty, moduly a balíčky  v Pythonu 
- [pandas]{.software}, [geopandas]{.software}, [polars]{.software}
- [matplotlib]{.software}, [plotnine]{.software}, [jupyter notebook]{.software}
- [Git]{.software}, [GitHub](https://www.github.com)
- [GitHub Copilot](https://github.com/features/copilot)
- programy s argumenty

## Prezentace{.presentations}

::: {#prezentace}
:::

## Zdroje{.sources}

- [GDAL/OGR Cookbook](https://pcjericks.github.io/py-gdalogr-cookbook/)
- [Geocomputation with Python](https://py.geocompx.org/)

## Data ke stažení{.data-sources}

- data [Natural Earth](https://www.naturalearthdata.com/)
  - [vektorová data](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip)
  - [rastrová data](https://naciscdn.org/naturalearth/10m/raster/HYP_HR_SR_W.zip)
- data **diamonds** - [https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv](https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv)


## Ukázkové kódy{.codes}

::: {#codes}
:::

## Instalace{.instals}

- management Pythonu - [Miniconda](https://docs.anaconda.com/free/miniconda/index.html) a nebo zde na webu info k instalaci [Conda](../tools/conda.qmd)
- IDE - [Visual Studio Code](https://code.visualstudio.com/)
- extenze pro VS Code - Python, Python Debugger, Black Formatter, isort, autopep8, Flake8, Mypy Type Checker, Pylance, Pylint, autoDocstring - Python Docstring Generator
- instalace Conda environmentu

Definice environment souboru, např. s názvem `env-pgis2.yaml`
```{.yaml include="./PGIS2/soubory/conda-environment.yml"}
```

Z conda prompt následně spustit:
```bash
conda create -f env-pgis2.yaml
conda activate pgis2
```

## Další 

- zřízení účtu na [Github](github.com), primárně na soukroumou e-mailovou adresu a následně doplnit studentskou adresu
- požádání o studentský přístup na Github dle [článku](https://techcommunity.microsoft.com/t5/educator-developer-blog/step-by-step-setting-up-github-student-and-github-copilot-as-an/ba-p/3736279)
- ověření nějakou dobou trvá cca. 1-2 dny
- následně se lze ve **VS Code** pomocí tohoto účtu přihlásit a měl by být dostupý **GitHub Copilot**  