---
title: Programování v GIS 4 (PvGIS4)
aliases: 
  - ./PGIS4/index.html
  - ./PGIS4/skripty/index.hmtl
  - ./PGIS4/prezentace/index.html
listing:
    - id: prezentace
      contents: PGIS4/prezentace
      sort-ui: false
      filter-ui: false
      type: table
      date-format: iso
      sort:
          - "date"
      fields: [date, title] 
      field-display-names:
          title: "Prezentace"
          date: "Datum"
          author: "Autor"
    - id: codes
      contents: PGIS4/skripty/description.yaml
      sort-ui: false
      filter-ui: false
      type: table
      date-format: iso
      sort:
          - "date"
          - "path"
      fields: [date, title] 
      field-display-names:
          title: "Skript"
          date: "Datum"
          author: "Autor"
---

## Řešená témata{.topics}

- základní přehled [QGIS]{.software}
- úvod [PyQGIS]{.software}
- zprovoznění Pythonu a QGIS Python API ve [VS Code]{.software} dle [návodu](../tools/osgeo4w.qmd#nastavení-python-prostředí-pro-visual-studiu-code-včetně-pythonu-i-qgis-python-api)
- vektorové vrstvy a práce s nimi
- geometrie `QgsGeometry` a `QgsAbstractGeometry`
- rastrová data
- processingové nástroje pro zpracování dat
- QGIS projekt a layout

## Seminární práce{.seminar-work}

Sestavte Python skript, které provede libovolné netriviální zpracování prostorových dat, dle vlastního výběru. Ve skriptu využijte knihovnu [QGIS Python API]{.software}. Záhlaví skriptu bude obsahovat popis funkčnosti - co skript dělá. Skript odevzdejte emailem před posledním cvičením. Funkčnost skriptu bude prezentována na posledním cvičení.

## Prezentace{.presentations}

::: {#prezentace}
:::

## Zdroje{.sources}

- [QGIS Python API documentation](https://qgis.org/pyqgis/master/)
- [QGIS Tutorials and Tips](https://www.qgistutorials.com/en/) - zejména kapitola **Python Scripting (PyQGIS)** ale i další zaměřené na [QGIS]{.software}
- [PyQGIS Developer Cookbook](https://docs.qgis.org/3.34/en/docs/pyqgis_developer_cookbook/index.html)

## Data ke stažení{.data-sources}

## Ukázkové kódy{.codes}

::: {#codes}
:::

## Další 

Doporučuji zřízení a otestování **GitHub Copilot** dle [návodu](../tools/github-copilot.qmd) pro zjednodušení psaní kódu v Pythonu.

Process nastavení PYthonu a QGIS pro [VS Code]{.software} je popsán [zde](../tools/osgeo4w.qmd#nastavení-python-prostředí-pro-visual-studiu-code-včetně-pythonu-i-qgis-python-api).

## Nastavení VS Code pro práci s QGIS API

V souboru `.vscode/settings.json` ve složce projektu přidejte:

```json
{
    "python.autoComplete.extraPaths": [
        "C:/OSGeo4W64/apps/qgis/python",
        "C:/OSGeo4W64/apps/qgis/python/plugins"
    ]
}
```

Pokud pracujete na Windows v [Conda]{.software} prostředí, bude cesta jiná, ale hledáte nadřazené složky, které obsahují soubory s příponou **.pyd**.