---
title: "Statistické modelování a testování"
subtitle: "Interpretace geodat"
author: "Jan Caha"
date: 2024-04-22
date-format: "YYYY-MM-DD"
format: 
    revealjs:
        theme: [../../reveal-custom.scss]
footer: "{{< var links.web >}}"
code-line-numbers: false
execute:
  echo: true
  eval: true
---

## Pojmy k modelování v [R]{.software}

- formula (vzorec) - zápis modelu v podobě `y ~ x1 + x2 + ...`
  - `y` je vysvětlovaná proměnná (závislá, výsledek)
  - `x1` - `xN` jsou vysvětlující proměnné (nezávislé, příčiny, prediktory)
  - zápis názvů proměnných (bez uvozovek) - používá se NSE
- ke vzorci se vždy ve funkci přidávají data ve formátu `data.frame`
  - např. lineární regrese: `lm(y ~ x1 + x2, data = data)` 

## Modelovací funkce

- značná část v základním [R]{.software}
- některé ve speciálních balíčcích
- problém s roztříštěností implementací těchto funkcí, nic není příliš sjednocené a velice komplikované na použití
- vzniká problém při složitějších analýzách, kde např. chceme jeden postup a model použít na více datových sadách

## Ujednocení modelování

- prvotní návrhy - balíky `broom` a `modelr`, které slouží pro zpracování výstupů modelů
- balík `tidymodels` - sjednocení framework modelování - [web](https://www.tidymodels.org/)
  - `recipes` - příprava dat
  - `parsnip` - specifikace modelu a interface pro práci s různými modely, existují k němu doplňovací balíčky pro konkrétní typy modelů
  - `dials` - specifikace parametrů modelu
  - `tune` - ladění hyperparametrů modelu
  - `yardstick` - vyhodnocení modelu
  - `workflows` - spojení všech kroků do jednoho objektu

## [tidymodels]{.software} postup



# Dotazy?{.center}