---
title: "Úvodní hodina"
subtitle: "Programování v GIS 3"
author: "Jan Caha"
date: 2025-09-16
year: 2025
date-format: "YYYY-MM-DD"
format: 
    revealjs:
        theme: 
          - ../../../clean.scss 
          - ../../../reveal-custom.scss
footer: "{{< var links.web >}}"
code-line-numbers: false
execute:
  echo: true
  eval: true
---

## Náplň

- programování v [Pythonu]{.software} s knihovnou [ArcPy]{.software} pro [ArcGIS Pro]{.software}
- zpracování a editace dat pomocí [ArcPy]{.software}, vektorová i rastrová data
- možnosti automatizace v [ArcGIS Pro]{.software} pomocí [ArcPy]{.software}
- vytváření skriptů a nástrojů pro [ArcGIS Pro]{.software} v [Pythonu]{.software}

## O čem to bude

- programování skriptů v Pythonu (funkce, objekty, atd.)
- práce s [ArcPy]{.software} a její [dokumentací](https://pro.arcgis.com/en/pro-app/latest/arcpy/get-started/what-is-arcpy-.htm)
- operace s geodaty skrze API [ArcPy]{.software}
- funkcionální i objektově orientované programování
- odchytávání výjimek - práce s nimi
  
## Dílčí úlohy

- použitelný a čitelný kód
- replikovatelné postupy
- programovací techniky a postupy
- debugování programů

## V čem budeme pracovat

- [VS Code]{.software}
- extenze pro [VS Code]{.software}
- management Pythonu skrze [Conda]{.software} přímo z [ArcGIS Pro]{.software}
- použití [GitHub Copilot AI]{.tool} viz [zde](../../../tools/github-copilot.qmd)

## Materiály

- prezentace
- kód z cvičení
- budou dostupné na [jancaha.github.io/vsb-vyuka/](jancaha.github.io/vsb-vyuka/)
- další materiály dle potřeby

## Z čeho vycházíme

- znalost Pythonu dle předmetu **Programování v GIS 2**
- znalost managementu Pythonu skrze [Conda]{.software}
- znalost [ArcGIS Pro]{.software} a jeho základních funkcí

## Zakončení předmětu

- test o dvou částech
- písemka - klíčové položky programování v Pythonu a [ArcPy]{.software}, interpretace kódu
- test týkající je interpretace a porozumění kódu (nahrazuje seminární práci)
  - zaměřené na bloky kódu o délce 10 - 15 řádků
  - otázky typu "co tento kód dělá?", "proč tento kód nefunguje?", "jak byste tento kód upravili, aby dělal X?", "splňuje tento kód zadání Y?"  

 
## GitHub Copilot

- budeme s ním zacházet opatrně
- nenahrazuje znalost programování
- je v pořádku ✅: napovídání, vysvětlování, revize kódu  
- není v pořádku ❌: generování celých úloh (problém juniorních programátorů), používání AI jako jediného zdroje informací (lepší využívat i dokumentaci) 
- uživatel by měl stále být ten kdo má kreativní kontrolu a představu, co a jak daný program řeší a případně to upravovat směrem k lepším řešením
- **Pravidlo: "Rozumím tomu, co píšu"**  -pokud nedokážete vysvětlit, co váš kód dělá, pravděpodobně byste ho neměli používat

# Dotazy?{.center}