---
title: "Obecné funkce [ArcPy]{.software}"
subtitle: "Programování v GIS 3"
author: "Jan Caha"
date: 2025-09-30
date-format: "YYYY-MM-DD"
format: 
    revealjs:
        theme: 
          - ../../../clean.scss 
          - ../../../reveal-custom.scss
footer: "{{< var links.web >}}"
code-line-numbers: false
execute:
  echo: true
  eval: true
---

## Popis objektu

- `arcpy.Describe()` - popis objektu (např. souboru, vrstvy, atd.), jako parameter slouží cesta k objektu
- výstupem je objekt, který obsahuje informace o daném objektu podle jeho typu (lehce komplikované, protože předem nevíme, co dostaneme - struktura odpovědi se liší podle typu objektu)

- `arcpy.da.Describe()` - modernější verze, která vrací python slovník (dictionary) s informacemi o objektu (mnohem lépe zpracovatelné a čitelnější)
- k informacím se přistupuje jako k hodnotám ve slovníku, např. `desc["dataType"]` 


## Popisy objektů

- `arcpy.da.Describe()` - - popis objektu dle zadaného názvu, lze i specifikovat typ objektu (pro případ shody názvů)
- výsledný objekty se liší dle požadovaného typu objektu - viz [dokumentace](https://pro.arcgis.com/en/pro-app/latest/arcpy/functions/describe.htm)
- základní minimum informací pro [všechny objekty](https://pro.arcgis.com/en/pro-app/latest/arcpy/functions/describe-object-properties.htm)

## Práce s `Describe()` objekty

- je vhodné naučit se přístupovat k proměnným objektu pomocí konstrukce

```{python}
# | eval: false
desc = arcpy.Describe("C:/data/soubor.shp")
if hasattr(desc, "dataType"):
    data_type = desc.dataType
    print(desc.dataType)
```

- předcházíme haváriím skriptu, pokud by objekt neměl danou vlastnost (proměnnou)

## Příklady

- vektorová data
- rastrová data
- další

## Funkce pro zjištění proměnných

- funkce vracející seznamy (i prázdné)
- typicky `arcpy.List*()`
- slouží pro zjišťování. tam kde programátor nemá předem představu o obsahu

## Příklad `arcpy.ListEnvironments()`

- vrací seznam proměnných geoprocessingu
- vše co je dostupné pod `arcpy.env.*`
- k proměnným se dostaneme pomocí `arcpy.env.proměnná` nebo `arcpy.env["proměnná"]`
- reset proměnných lze provést pomocí `arcpy.ResetEnvironments()`

## Příklady - výpisy dat

- `arcpy.ListDatasets()`
- `arcpy.ListFeatureClasses()`
- `arcpy.ListFields()`
- `arcpy.ListFiles()`
- `arcpy.ListIndexes()`
- `arcpy.ListRasters()`
- `arcpy.ListTables()`
- `arcpy.ListWorkspaces()`

## Licence a instalace

- kontroly dostupnosti licencí a stavu instalace
- `arcpy.CheckExtension()` - je exteze dostupná?
- `arcpy.CheckInExtension()`, `arcpy.CheckOutExtension()` - pro sdílené licence
- `arcpy.CheckProduct()` - dostupná úroveň licence + info
- `acpy.GetInstallInfo()` - info o instalaci
- `arcpy.ListInstallations()` - typy instalací

# Dotazy?{.center}
