install.packages(c(
    "tidyverse",
    "here",
    "sf",
    "terra",
    "stars",
    "tmap",
    "lwgeom",
    "qgisprocess",
    "remotes",
    "tidymodels",
    "DT",
    "rmarkdown",
    "plotly",
    "tidymodels",
    "easystats"
))

remotes::install_github("JanCaha/r_package_qgis")
