name: Build website and deploy

on: [push]

jobs:

  build-web-and-deploy:

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          channels: conda-forge
          activate-environment: env-project
          environment-file: conda-environment.yml
      
      - name: Setup CRAN Binaries
        run: |  
          sudo wget -q -O- https://eddelbuettel.github.io/r2u/assets/dirk_eddelbuettel_key.asc | sudo tee -a /etc/apt/trusted.gpg.d/cranapt_key.asc
          sudo echo \"deb [arch=amd64] https://r2u.stat.illinois.edu/ubuntu jammy main\" > /etc/apt/sources.list.d/cranapt.list
          sudo apt-get apt-get install -y r-base r-cran-sf r-cran-terra r-cran-stars r-cran-tidyverse r-cran-tidymodels r-cran-here

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install extensions
        run: ./install.sh  

      - name: Render Quarto
        run: quarto render .    
      
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  