name: Build website and deploy

on:
  push:
    branches: 
      - main

jobs:

  build-web-and-deploy:

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

- name: Cache Conda
        uses: actions/cache@v3
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('conda-environment.yml') }}
          restore-keys: ${{ runner.os }}-conda-

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: env-project
          environment-file: conda-environment.yml
use-only-tar-bz2: true
      
      - name: Cache APT packages
        uses: actions/cache@v2
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('linux_install_R.sh') }}
          restore-keys: ${{ runner.os }}-apt-
      
      - name: Install R and packages
        run: |
          sudo ./linux_install_R.sh  --all

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install extensions
        run: ./install.sh  

      - name: Render Quarto
        run: quarto render .    
      
      - name: Publish to GitHub Pages
        if: 
          contains('refs/heads/main', github.ref)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  