name: Build website and deploy

on:
  push:
    branches: 
      - main

jobs:

  build-web-and-deploy:

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          activate-environment: env-project
          environment-file: conda-environment.yml
      
      - name: Install R and packages
        run: |
          sudo ./linux_install_R.sh  -a

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install extensions
        run: ./install.sh  

      - name: Render Quarto
        run: quarto render .    
      
      - name: Publish to GitHub Pages
        if: 
          contains('refs/heads/main', github.ref)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  