name: Build website and deploy

on:
  push

jobs:

  build-web-and-deploy:

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash -l {0}
  
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4


      - name: Install Jupyter
        run: python3 -m pip install jupyter
          
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          channels: conda-forge
          activate-environment: env-project
          environment-file: conda-environment.yml
      
      - name: Conda info
        run: |
          conda info    

      #- name: Install R
      #  uses: r-lib/actions/setup-r@v2

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install extensions
        run: ./install.sh  

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  