name: Build website and deploy

on:
  push

jobs:

  build-web-and-deploy:

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash -l {0}
  
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      #- name: Install R
      #  uses: r-lib/actions/setup-r@v2

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
      
      - name: Conda init
        run: conda init

      - name: Create conda env
        run: conda env create -f conda-environment.yml
      
      - name: Activate conda env 
        run:  conda activate env-project

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install extensions
        run: ./install.sh  

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  