name: Test R examples

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: push

jobs:

  test-r-examples:

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write
    
    env:
      APT_CACHE_DIR: ~/apt_cache
      CONDA_PKG_DIR: ~/conda_pkgs_dir
      R_LIBS_USER: /tmp/Rlibs
      DEBIAN_FRONTEND: noninteractive
      QT_QPA_PLATFORM: offscreen 

    steps:

      - name: ATP download settings
        run: |
          grep "Dir::Cache" /etc/apt/apt.conf.d/*
          echo 'APT::Keep-Downloaded-Packages "true";' | sudo tee /etc/apt/apt.conf.d/10keep-cache

      - name: R env setup
        run: |
          mkdir -p $R_LIBS_USER
          echo "R_LIBS_USER=$R_LIBS_USER" > $HOME/.Renviron
          cat $HOME/.Renviron

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Pandoc
        run: |
          sudo apt-get -y install pandoc
          pandoc --version

      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: ${{ env.APT_CACHE_DIR}}
          key: ${{ runner.os }}-apt-${{ hashFiles('linux_install_R.sh') }}
          restore-keys: ${{ runner.os }}-apt-

      - name: Install R and packages
        run: |
          sudo ./linux_install_R.sh  --all
      
      - name: IDG skripty
        run: |
          FILES="./subjects/IDG/skripty/*.R"
          for FILE in $FILES
          do
            echo "--------------------"
            echo "*** $FILE ***"
            Rscript $FILE 
          done    
          FILES="./subjects/IDG/skripty/*.Rmd"
          for FILE in $FILES
          do
            echo "--------------------"
            echo "*** $FILE ***"
            Rscript -e "rmarkdown::render('$FILE')" 
          done