name: Test Python examples

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
on: 
  push:
    paths:
      - '.github/workflows/test_python_examples.yaml'
      - '**.py'

jobs:

  test-python-examples:

    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write

    env:
      CONDA_PKG_DIR: ~/conda_pkgs_dir
      R_LIBS_USER: /tmp/Rlibs
      DEBIAN_FRONTEND: noninteractive
      QT_QPA_PLATFORM: offscreen 

    steps:

      - name: Set Env
        run: |
          echo "APT_CACHE_DIR=$RUNNER_TEMP/apt_cache" >> $GITHUB_ENV
          echo "MONTH=$(date +%B)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Conda
        uses: actions/cache@v4
        env:
          CACHE_NUMBER: 0
        with:
          path: ${{ env.CONDA_PKG_DIR }}
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('conda-environment.yml') }}-${{ env.MONTH }}
          restore-keys: ${{ runner.os }}-conda-

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: pgis2
          environment-file: subjects/PGIS2/soubory/conda-environment.yml
          pkgs-dirs: ${{ env.CONDA_PKG_DIR }}
      
      - name: Check if PGIS2 folder was modified
        id: pgis2_modified
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^subjects/PGIS2/'; then
            echo "PGIS2_MODIFIED=true" >> $GITHUB_ENV
            echo "modified=true" >> $GITHUB_OUTPUT
          else
            echo "PGIS2_MODIFIED=false" >> $GITHUB_ENV
            echo "modified=false" >> $GITHUB_OUTPUT
            echo "Not running steps for PGIS2!!!"
          fi
      - name: Test
        run: echo ${{ steps.pgis2_modified.outputs.modified }}

      - name: PGIS2 data
        if: env.PGIS2_MODIFIED == 'true'
        run: |
          ./subjects/PGIS2/soubory/get_data.sh

      - name: PGIS2 skripty
        if: env.PGIS2_MODIFIED == 'true'
        run: |
          FILES="./subjects/PGIS2/skripty/*.py"
          for FILE in $FILES
          do
            echo "--------------------"
            echo "*** $FILE ***"
            python3 $FILE > /dev/null
          done

      - name: Check if PGIS4 folder was modified
        id: pgis4_modified
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^subjects/PGIS4/'; then
            echo "PGIS4_MODIFIED=true" >> $GITHUB_ENV
          else
            echo "PGIS4_MODIFIED=false" >> $GITHUB_ENV
            echo "Not running steps for PGIS4!!!"
          fi

      - name: Add qgis to Conda
        if: env.PGIS4_MODIFIED == 'true'
        run: |
          conda install qgis

      - name: PGIS4 data
        if: env.PGIS4_MODIFIED == 'true'
        run: |
          ./subjects/PGIS4/soubory/get_data.sh
      
      - name: PGIS4 skripty
        if: env.PGIS4_MODIFIED == 'true'
        run: |
          FILES="./subjects/PGIS4/skripty/*.py"
          for FILE in $FILES
          do
            echo "--------------------"
            echo "*** $FILE ***"
            if grep -q "# no GA run" $FILE; then
                echo "Skipping file on GA."
            else
              # this causes SEGFAULT in Python for the installed version so we remove it from the scripts
              sed -i -e 's/qgis.exitQgis()/#qgis.exitQgis()/g' $FILE
              python3 $FILE > /dev/null
            fi
            
          done    