name: Test Python examples

on: push

jobs:

  test-python-examples:

    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write

    steps:

      - name: Modify environment Qt mainly
        run: | 
           echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
           echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
    
      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          activate-environment: pgis2
          environment-file: subjects/PGIS2/soubory/conda-environment.yml
      
      - name: PGIS2 data
        run: |
          ./subjects/PGIS2/soubory/get_data.sh

      - name: PGIS2 skripty
        run: |
          FILES="./subjects/PGIS2/skripty/*.py"
          for FILE in $FILES
          do
            echo "--------------------"
            echo "*** $FILE ***"
            python3 $FILE 
          done

      - name: Add qgis to Conda
        run: |
          conda install qgis

      - name: PGIS4 data
        run: |
          ./subjects/PGIS4/soubory/get_data.sh
      
      - name: PGIS4 skripty
        run: |
          FILES="./subjects/PGIS4/skripty/*.py"
          for FILE in $FILES
          do
            echo "--------------------"
            echo "*** $FILE ***"
            python3 $FILE 
          done    