name: Test PostgreSQL examples

on: push

jobs:

  test-postgresql-examples:

    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgis/postgis:16-master
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: heslo
          PGDATA: /data/postgres
        volumes:
          - /tmp:/tmp
        ports:
          - 5432:5432

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write
    
    steps:
      
      - name: Stop Postgres
        run: sudo service postgresql stop

      - name: Checkout
        uses: actions/checkout@v4

      - name: Pip install psycopg
        run: |
          pip install psycopg

      - name: PG CONN ENV
        run: |
          echo "PG_CONN="dbname=postgres host=localhost user=postgres port=5432 password=heslo"" >> $GITHUB_ENV
      
      - name: Test
        run: |
          python3 -c 'import psycopg; import os; psycopg.connect(os.getenv("PG_CONN"))'
        
      - name: Install GDAL
        run: |
          sudo apt-get -y install gdal-bin
            
      - name: PDBS2 data
        run: |
          cp -r ./subjects/PDBS2/soubory/ /tmp/postgres/
          ls -l /tmp/postgres
      
      - name: Import spatial data to Postgis
        run: |
          cd subjects/PDBS2/soubory
          ../skripty/02_load_data_to_postgis.sh
      
      - name: Run Examples
        run: |
          python3 subjects/PDBS2/soubory/sql_scripts_runner.py subjects/PDBS2/skripty "$PG_CONN"
