name: Test Python examples

on: push

jobs:

  test-python-examples:

    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write

    env:
      APT_CACHE_DIR: ~/apt_cache
      CONDA_PKG_DIR: ~/conda_pkgs_dir
      R_LIBS_USER: /tmp/Rlibs
      DEBIAN_FRONTEND: noninteractive
      QT_QPA_PLATFORM: offscreen 

    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cache Conda
        uses: actions/cache@v4
        env:
          CACHE_NUMBER: 0
        with:
          path: ${{ env.CONDA_PKG_DIR }}
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('conda-environment.yml') }}
          restore-keys: ${{ runner.os }}-conda-

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: pgis2
          environment-file: subjects/PGIS2/soubory/conda-environment.yml
          pkgs-dirs: ${{ env.CONDA_PKG_DIR }}
      
      - name: PGIS2 data
        run: |
          ./subjects/PGIS2/soubory/get_data.sh

      - name: PGIS2 skripty
        run: |
          FILES="./subjects/PGIS2/skripty/*.py"
          for FILE in $FILES
          do
            echo "--------------------"
            echo "*** $FILE ***"
            python3 $FILE > /dev/null
          done

      - name: Add qgis to Conda
        run: |
          conda install qgis

      - name: PGIS4 data
        run: |
          ./subjects/PGIS4/soubory/get_data.sh
      
      - name: PGIS4 skripty
        run: |
          FILES="./subjects/PGIS4/skripty/*.py"
          for FILE in $FILES
          do
            echo "--------------------"
            echo "*** $FILE ***"
            if grep -q "# no GA run" $FILE; then
                echo "Skipping file on GA."
            else
              # this causes SEGFAULT in Python for the installed version so we remove it from the scripts
              sed -i -e 's/qgis.exitQgis()/#qgis.exitQgis()/g' $FILE
              python3 $FILE > /dev/null
            fi
            
          done    