name: Test examples

on: push

jobs:

  test-python-examples:

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          activate-environment: env-project
          environment-file: conda-environment.yml
      
      - name: PGIS2 data
        run: |
          ./PGIS2/soubory/get_data.sh

      - name: PGIS2 skripty
        run: |
          FILES="./PGIS2/skripty/*.py"
          for FILE in $FILES
          do
            echo "--------------------"
            echo "*** $FILE ***"
            python3 $FILE 
          done
 
  test-r-examples:

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write
    
    env:
      R_LIBS_USER: /tmp/Rlibs

    steps:
      
      - name: Test var
        run:
          echo $R_LIBS_USER
          mkdir -p $R_LIBS_USER
          ls -l $R_LIBS_USER
          echo $HOME

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: R apt
        run: |
          sudo wget -q https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc -O /etc/apt/trusted.gpg.d/marutter_pubkey.asc
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/marutter_pubkey.asc] https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/" | sudo tee /etc/apt/sources.list.d/r.list
          sudo apt-get update
          sudo apt-get install -y r-base

      - name: R location
        run: |
          Rscript -e "Sys.getenv('R_LIBS_USER')"
          Rscript -e ".libPaths()"

      - name: Setup CRAN Binaries
        run: |  
          sudo wget -q https://eddelbuettel.github.io/r2u/assets/dirk_eddelbuettel_key.asc -O /etc/apt/trusted.gpg.d/cranapt_key.asc
          echo "deb [arch=amd64] https://r2u.stat.illinois.edu/ubuntu jammy main" | sudo tee /etc/apt/sources.list.d/cranapt.list
          sudo apt-get update
          sudo apt-get install -y r-cran-sf r-cran-terra r-cran-stars r-cran-tidyverse r-cran-tidymodels r-cran-here r-cran-rmarkdown
      
      - name: IDG skripty
        run: |
          FILES="./IDG/skripty/*.R"
          for FILE in $FILES
          do
            echo "--------------------"
            echo "*** $FILE ***"
            Rscript $FILE 
          done    
          FILES="./IDG/skripty/*.Rmd"
          for FILE in $FILES
          do
            echo "--------------------"
            echo "*** $FILE ***"
            Rscript -e "rmarkdown::render('$FILE')" 
          done 